import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/russian.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>EGE.online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-apple123 text-xl">EGE.online</h1>
            <ul className="flex items-center">
              <li>
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Войти
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              EGE.online
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Полезные материалы ЕГЭ
            </h3>
          </div>
        </section>
        <section>

          <div className="lg:flex gap-10 justify-center mx-auto">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 text-white dark:bg-[#242E38] flex-0">
              <Image src={deved} width={150} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Русский язык
              </h3>
              <p className="py-2">
                Полезные материалы по Русскому зыку
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 text-white dark:bg-[#242E38] flex-0">
              <Image src={deved} width={150} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Русский язык
              </h3>
              <p className="py-2">
                Полезные материалы по Русскому зыку
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 text-white dark:bg-[#242E38] flex-0">
              <Image src={deved} width={150} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Русский язык
              </h3>
              <p className="py-2">
                Полезные материалы по Русскому зыку
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
