import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { BsFillMoonStarsFill, BsTelegram } from "react-icons/bs";
import { MdMenuBook } from "react-icons/md";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ЕГЭ.online</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" text-white bg-[#1A2026] font-apple123">
        <section className="min-h-screen">
          <nav className="p-4 flex bg-[#212932] justify-between">
              <h1 className="text-2xl ml-2">EGE.online</h1>
            <ul className="flex items-center">
              <li>
                <a
                  className="bg-[#248BDA] hover:bg-[#207CC2] text-white px-5 py-2 border-spacing-1 rounded-md ml-8"
                  href="#"
                >
                  Войти
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 font-medium">EGE.online</h2>
            <h3 className="text-2xl py-2">
              Полезные материалы для подготовки к ЕГЭ
            </h3>
          </div>
        </section>
      </main>
    </div>
  );
}
